### ISSUE TITLE
GiT branch with slash in their name will throw an error (releaseNotesDraftFolder)

### ISSUE THREAD

**Issue by labbedaine** [AmadeusITGroup/sbt-release-notes#50]
Hi!
First of all, thank you very much for that library. I did not know I needed it until I found it.

In my my project we use the following naming convention for our GiT branches.

```
1. doc/TICKET-NUMBER_describeYourWork
2. feature/TICKET-NUMBER_describeYourWork
3. fix/TICKET-NUMBER_describeYourWork
```

If I call `sbt releaseNotesDraft` it throws an error (for obvious reason!)

-- Example --
**Branch is**: `feature/test-release-notes`

`[error] (releaseNotesDraft) java.io.FileNotFoundException: /my-project/release-notes/release_feature/test-release-notes.md (No such file or directory)
`
-- /Example --

FYI. If I don't use "/" in the branch name the plugin behave correctly except with that git problem that I couldn't figure out.  Note that my main branch is set to "master", the branch exists but is currently empty.
```
fatal: ambiguous argument 'main..feature-release-notes': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

I don't think there's a setting to control the .md file name but if there was one I could replace the _slash_ by _underscore_ or the plugin could handle special cases like that out-of-the-box (_if possible_). 

If you need more details or if I can contribute in any way please let me know (_however I never wrote an SBT plugin in my life_)

Again, thank you very much for that work!

**Comment by generoso** [comment]
Hey @labbedaine! Thanks for using this plugin and reporting this issue :) 
I've just created this PR that should fix it: https://github.com/AmadeusITGroup/sbt-release-notes/pull/51
I also added a test that should cover your use case.
I let you have a look at it. Thanks for your feedback ;)

**Comment by labbedaine** [comment]
Wow that's lightning fast service, haha!  I think the [release failed](https://github.com/AmadeusITGroup/sbt-release-notes/actions/runs/12073656121/job/33670197333) hence v.0.0.3 is not available yet in the Maven repo.

**Comment by generoso** [comment]
Fixing the CICD :) Thanks to you I've just discovered that they recently added mandatory token auth for sonatype.

**Comment by labbedaine** [comment]
⚡ Fixed in v0.0.3 👍🏻 

I will now turn my attention to `sbt releaseNotesDraft`

```
fatal: ambiguous argument 'main..feature/XX-1234_MyFeature': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

🙏🏻

**Comment by generoso** [comment]
The git error you are getting is most likely due to the fact that maybe you did not set the `releaseNotesBranch` parameter (default is "main"). As your main branch is master, you should set `releaseNotesBranch := "master"` as explained in the README.

**Comment by labbedaine** [comment]
I read your README from top to bottom twice (_great job on the documentation btw_!), I swear **_releaseNotesBranch_** is set to "master".  I am not at home but I can take a screenshot of the configuration when I get back.

**Comment by generoso** [comment]
Just to be sure, you can a sanity check, to be sure your config is fine:

Enter an sbt shell (from your project dir type `sbt` in a terminal), and then type `releaseNotesBranch` to inspect its value. You should see something like:
```
[info] releaseNotesBranch
[info] 	master
```
If you see `main` there, you have a problem with your config.

**Comment by labbedaine** [comment]
Thanks for sharing, that's helpful.

My settings are:
![image](https://github.com/user-attachments/assets/9325386b-1d3e-437c-bbae-348fa9ace951)

Results of the CLI command `releaseNotesBranch`
```
sbt:root> releaseNotesBranch
[info] core / releaseNotesBranch
[info]  main
[info] slack / releaseNotesBranch
[info]  main
[info] teams / releaseNotesBranch
[info]  main
[info] releaseNotesBranch
[info]  master
sbt:root> 
```


So as you can see, I am using a multi-module project and I apply the settings to the **_root_** only which might be the problem.

**Comment by generoso** [comment]
Try with: ` ThisBuild / releaseNotesBranch := "master"`

**Comment by generoso** [comment]
You're welcome :) Enjoy the plugin and have a nice weekend too!
